version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: bookprep_postgres
    environment:
      POSTGRES_USER: bookprep_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bookprep
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: bookprep_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    volumes:
      - miniodata:/data

volumes:
  pgdata:
  miniodata:
