services:
  postgres:
    image: postgres:16
    container_name: palabra_postgres
    environment:
      POSTGRES_USER: palabra
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: palabra
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: palabra_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    volumes:
      - miniodata:/data

  redis:
    image: redis:7
    container_name: palabra_redis
    ports:
      - "6379:6379"

  dbmate:
    image: amacneil/dbmate:latest
    container_name: palabra_dbmate
    environment:
      DATABASE_URL: postgres://palabra:secret@postgres:5432/palabra?sslmode=disable
      DBMATE_MIGRATIONS_DIR: /db/migrations
    volumes:
      - ./services/api/db:/db
    depends_on:
      - postgres

  tika:
    image: apache/tika:3.2.3.0-full
    container_name: tika
    ports:
      - "9998:9998"
    restart: always

  rq-worker:
    build: ./services/worker
    command: ["worker"]
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MINIO_BUCKET=palabra
      - DB_URL=postgresql+psycopg2://palabra:secret@postgres:5432/palabra
    depends_on:
      - redis
      - postgres
      - minio

  worker-api:
    build: ./services/worker
    command: ["api"]
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MINIO_BUCKET=palabra
      - DB_URL=postgresql+psycopg2://palabra:secret@postgres:5432/palabra
    depends_on:
      - redis
      - postgres
      - minio
    ports:
      - "8001:8000"

volumes:
  pgdata:
  miniodata:
